[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
startCommand = "sh -c 'pnpm prisma migrate deploy && node .output/server/index.mjs'"
healthcheckPath = "/healthcheck"
restartPolicyType = "ON_FAILURE"
numReplicas = 1
